[package]
name = "rtunel"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
async-trait = "0.1.88"
base64 = "0.22.1"
boring = "4.15.0"
boring-sys = "4.22.0"
brotli = "8.0"
clap = { version = "4.5.38", features = ["derive"] }
foreign-types = "0.5.0"
futures-util = "0.3.31"
hex = "0.4.3"
md5 = "0.7.0"
serde = { version = "1.0.219", features = ["derive"] }
sha2 = "0.10.9"
tokio = { version = "1.45.1", features = ["full"] }
tokio-boring = "4.15.0"
tokio-quiche = { version = "0.19.0", default-features = false }
tokio-stream = "0.1.17"
toml = "0.8.22"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
uuid = { version = "1.11.0", features = ["serde", "v4"] }
